---
- name: Patching Playbook
  hosts: all
  become: true
  tasks:
    - name: Performing the pre-check operations.
      script: /home/ansadmin/precheck.sh
      args: 
          creates: /home/ansadmin/precheck.sh
    
    - name: Applying all the available patches.
      apt:
          name: "*"
          state: latest
    - name: Rebooting the machines.
      reboot:
        reboot_timeout: 6000

    - name: Performing the post-check operations.
      script: /home/ansadmin/postcheck.sh
      args: 
          creates: /home/ansadmin/postcheck.sh

    - name: Finding the pre & post check result files.
      shell: (cd /home/ansadmin; find . -maxdepth 1 -type f -iname "*.txt") | cut -d'/' -f2
      register: files_to_fetch

    - name: Fetching the result files.
      fetch:
        src: /home/ansadmin/{{ item }}
        dest: /home/ansadmin 
      with_items: "{{ files_to_fetch.stdout_lines }}"


